### ISSUE TITLE
RELAY_PORT seem to be ignored

### ISSUE THREAD

**Issue by eleaner** [HolgerHatGarKeineNode/haven-docker#1]
whatever port i will set I still see listening at` http://localhost:3355`

what am I doing wrong?

**Comment by eleaner** [comment]
shut, it is not part of v0.4.1
that would explain

**Comment by HolgerHatGarKeineNode** [comment]
```
    ports:
      - "3355:3355"
```

Within the docker-compose.yml, the port that is exposed to the outside can be set on the left-hand side.

In the container itself, the port remains fixed at 3355, so port 3355 will always be output in the container's LOG, although the Docker container itself can then be reached from the outside via a different port.

```
    ports:
      - "8080:3355"
```

This setting would release the server to the outside on port 8080. Port 3355 would still appear in the logs because it lives inside the container.

**Comment by HolgerHatGarKeineNode** [comment]
You can find the documentation here: https://docs.docker.com/get-started/docker-concepts/running-containers/publishing-ports/

**Comment by eleaner** [comment]
I need to use host networkBut compiling the latest version helped Thank you Sent from my iPhoneOn 29 Oct 2024, at 09:36, The Ben 'notifications at github.com' ***@***.***> wrote:﻿
    ports:
      - "3355:3355"

Within the docker-compose.yml, the port that is exposed to the outside can be set on the left-hand side.
In the container itself, the port remains fixed at 3355, so port 3355 will always be output in the container's LOG, although the Docker container itself can then be reached from the outside via a different port.
    ports:
      - "8080:3355"

This setting would release the server to the outside on port 8080. Port 3355 would still appear in the logs because it lives inside the container.
